name: Local CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run pulled docker image
        uses: docker://swift:latest
      - name: Update package manager
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -yq libssl-dev pkg-config libcurl4
      - name: Build project
        run: swift build -v
      - name: Run tests
        run: swift test

  build-macos:
    name: Build macOS
    runs-on: macos-12
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build project
        run: swift build -v
      - name: Run tests
        run: swift test
