name: Local CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ubuntu:
    name: Build Ubuntu
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run pulled docker image
        uses: docker://swift:5.7-jammy
      - name: Update package manager
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install -yq libssl-dev pkg-config libcurl4
      - name: Build project
        run: swift build -v
      - name: Run tests
        run: swift test

  build-macos:
    name: Build macOS
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build project
        run: swift build -v
      - name: Run tests
        run: swift test
